### ISSUE TITLE
Clarifying human readable for new users

### ISSUE THREAD

**Issue by hoytpr** [datacarpentry/wrangling-genomics#101]
On the exercise starting at line 215, the "Hint" is at least partially for learning the -h option. But to avoid confusion the use of "M" and "G" should be Mb and Gb. Suggest the line 238 read:
"There are six FASTQ files ranging from 840M (840MB) to 4.0G (4.0GB)".  

Justification: New learners may have never seen the -h option before, and need to keep MB and GB distinct from Mbp or Gbp. Consistency in these designations will be important at this point in the lecture.

**Comment by ErinBecker** [comment]
Thanks @hoytpr. Agreed that this is very important thing to keep clear when working with Genomics data!
