### ISSUE TITLE
Typos in 00-quality-control.md

### ISSUE THREAD

**Issue by hoytpr** [datacarpentry/wrangling-genomics#103]
TYPOS found in 00-quality-control.md

line 49: "its" should be "it's"
line 79: "eg" should be "e.g."
line 144: "begining" should be "beginning"
line 424: remove one of the "four" 
line 427 "unziped" should be "unzipped"
line 560: "termperature" should be "temperature"

**Comment by fpsom** [comment]
Thanks @hoytpr ! I've just edited `00-quality-control.md` and fixed all typos!
