### ISSUE TITLE
Lesson "automation": better syntax for variable handling and a typo/mistake?

### ISSUE THREAD

**Issue by DennisCoding** [datacarpentry/wrangling-genomics#108]
I have two issues with the automation course:

First issue:
IMHO the shown method to concatenate a bash variable and plain text is not the recommended way. See this excerpt from the lesson:

> $ for infile in *.fastq
> do
> **outfile=$infile\_trim.fastq**
> java -jar ~/Trimmomatic-0.32/trimmomatic-0.32.jar SE $infile $outfile SLIDINGWINDOW:4:20 MINLEN:20
> done

This kind of operation (bold in the example above) should be done via the ${variable} syntax, and not via an escape character (i.e. $variable\_plain_text). Earlier courses teach the ${variable} syntax method, so also for consistency I think this should be changed. Or am I missing something?

Second issue:
I might have found a typo/mistake, but I`m not 100% sure and I have no VM to test it (anymore). So if someone could confirm I'd be most obliged. But, in the exercise quoted below:

> Vizualize the alignment of the reads for our SRR098281.fastq_trim.fastq_small sample. What variant is present at position 145? What is the canonical nucleotide in that position?

Shouldn't this be position 146? Or did I miscount or became confused between 0-counting programs and 1-counting programs?

Kind regards,
Dennis

**Comment by crazyhottommy** [comment]
Hi @DennisCoding ,

For issue 1, I had mentioned it here https://github.com/datacarpentry/wrangling-genomics/issues/81
and should have fixed it by this commit https://github.com/datacarpentry/wrangling-genomics/commit/18eec4a6518867f1ecc21da70abcdee2a250a768

Not sure for the second issue.

Thank you,
Tommy

**Comment by fpsom** [comment]
Thanks @DennisCoding for pointing this out. I've just put a [PR](https://github.com/datacarpentry/wrangling-genomics/pull/109) addressing your first point, 

Regarding your second point, I also do not have access to the VM, but in any case I am not really sure it is an issue; the point of the exercise it to be able to view a specific position using `tview`, so the actual number does not really matter and as far as I can see, it is consistent.

**Comment by fpsom** [comment]
Thanks again @DennisCoding ! I am closing this issue now, given that it has been addressed in the PR.
