### ISSUE TITLE
Using bwa mem instead of bwa aln in 02-variant_calling.md

### ISSUE THREAD

**Issue by taylorreiter** [datacarpentry/wrangling-genomics#111]
In [datacarpentry/wrangling-genomics/_episodes/02-variant_calling.md](https://github.com/datacarpentry/wrangling-genomics/blob/gh-pages/_episodes/02-variant_calling.md), `bwa aln` is taught instead of `bwa mem`. I see the note about `bwa mem`, but I think most people who will be taking this work shop will be working with reads >50bp. I think teaching `bwa mem` instead of `bwa aln` > `bwa samse` will simplify the learning process & lesson time, and give the learners a better understanding of the pipeline they will probably use when they do alignment with their own data. Thoughts?

**Comment by standage** [comment]
+1

We did this last year at CSUMB. The SAI/SAM two-step is an extra step that the learners simply have to "trust us" is necessary. And unless they're going to be working with very short reads in the future, they're going to be using BWA MEM in the future anyway.

Note that to keep things consistent, it might be worth identifying/creating a new sample data set with 2x75 bp or 2x100 bp reads, for which BWA MEM would be indisputably the better choice.

**Comment by taylorreiter** [comment]
Rewrote for UC Davis Genomics workshop here:
https://github.com/taylorreiter/wrangling-genomics/blob/gh-pages/_episodes/02-variant_calling.md

**Comment by standage** [comment]
Was this submitted as a PR? I'm getting this when I try to compare `taylorreiter/wrangling-genomics` to `datacarpentry/wrangling-genomics`.

<img width="1040" alt="screen shot 2018-04-13 at 9 55 03 am" src="https://user-images.githubusercontent.com/566823/38747773-cc56084c-3f00-11e8-9225-9209a25587fc.png">

**Comment by taylorreiter** [comment]
no...only #115 was merged. I'm confused why you got that page

**Comment by taylorreiter** [comment]
@fpsom is this an issue I can submit a PR for?

**Comment by fpsom** [comment]
@taylorreiter yes please!

**Comment by ErinBecker** [comment]
This change has been [approved by the Curriculum Advisors.](https://github.com/datacarpentry/curriculum-advisors/blob/master/genomics/september-2018-genomics-minutes.md) in conjunction with the transfer to a new data set. @taylorreiter.

**Comment by fpsom** [comment]
I think this issue has been resolved now! @ErinBecker @taylorreiter should we close the issue?

**Comment by ErinBecker** [comment]
Yes! Thanks for the ping @fpsom.
