### ISSUE TITLE
trimming parameters are very stringent

### ISSUE THREAD

**Issue by taylorreiter** [datacarpentry/wrangling-genomics#113]
In the wrangling-genomics episodes, the goal is variant calling. In this pipeline, we are using a well-defined reference genome. By using `SLIDINGWINDOW:4:20`, we are throwing out a lot of information that could be used for the variant calling workflow. Perhaps we should suggest using more lenient parameters like `SLIDINGWINDOW:4:2` like those put forth by the [McMannes paper](https://doi.org/10.3389/fgene.2014.00013) (even though this is for mRNA), as suggested by @ljcohen.

**Comment by ljcohen** [comment]
http://dibsi-rnaseq.readthedocs.io/en/latest/quality-trimming.html

**Comment by fpsom** [comment]
Thanks @taylorreiter @ljcohen for the comments (and the reference). Although I generally agree with this change, I have two counter-arguments to this:
1. The goal is indeed variant calling, but also to have a few clear-cut instances of SNPs that we can follow-up on in the next episode. So an explanation on the impact that the `PHRED` value has on the number of SNPs is important, but for training purposes it makes sense for me to keep it more stringent.
2. The actual coverage of the input data used is quite low (if I recall correctly). So having a high threshold could actually improve the SNP calling.

Both arguments are based on the same paper:
> _What is apparent, is that for typically-sized datasets, trimming at PHRED = 2 or PHRED = 5 optimizes assembly quality. The exception to this rule appears to be in studies where the identification of SNP markers from high (or very low) coverage datasets is the primary goal._

Thoughts?

**Comment by taylorreiter** [comment]
Hi @fpsom, I see the above arguments you have laid out and think they have merit.  I see how it is most appropriate to use stringent trimming given that the data are low coverage. My concern is that the learners are not trimming a subsampled dataset, but instead trim the complete SRA files. Then, a hidden directory is copied (or symbolically linked) into a directory with the reference genome to complete the variant calling pipeline, in which there are subsampled and pre-trimmed reads. I like this, as in our workshop we were only able to trim one file, and because subsampling is necessary for the commands to run in a timely manner. I think we could give them a stringently trimmed file, but teach them to trim less stringently. In most cases, I think the learners will be working with coverage that is higher than 2x (the approximate coverage of the subsampled reads we give them for variant calling), and so I am more interested in teaching them an application that will be most appropriate for their future data. 

Could we teach them to trim leniently, and then mention that the data set we are using going forward in the lesson was stringently trimmed because that was best for our specific application? Would this add confusion?

Thoughts?

**Comment by fpsom** [comment]
Hi @taylorreiter. Actually that makes a lot of sense; the command itself can remain the same, but a note explicitly mentioning the difference between the "training exercise" and the actual application would be very useful.

Do you think that you could put a PR that would add this information (possibly with the reference as well)? If pressed for time, I can put something together later for review.

**Comment by taylorreiter** [comment]
@standage how does this fit into things you're thinking about? Should I put something together for this or hold off for now?

**Comment by standage** [comment]
In my testing with the new docker image on https://github.com/datacarpentry/genomics-workshop/pull/44, I used stringent parameters. This is a bit orthogonal to that effort. :-)

**Comment by taylorreiter** [comment]
Addressed by #133! @fpsom can we close this?

**Comment by fpsom** [comment]
Yes, for sure I think we can safely close this. Thanks @taylorreiter !
