### ISSUE TITLE
Need to prep learners for `basename` in the automation lesson

### ISSUE THREAD

**Issue by standage** [datacarpentry/wrangling-genomics#117]
I taught the automation lesson in a recent workshop at UC Davis, and one of the pain points was the use of the `basename` command. A couple of factors made this pretty challenging.

- The command is introduced without explanation or motivation at a critical point in the lesson. Students are struggling to wrap their minds around the synthesis of a bunch of things we've just taught them, and this additional complexity is substantial.
- Normally, I would've tried to take a moment and explain in more depth how the command works and what it's used for before proceeding. However, we were pressed for time so this wasn't really an option.

I felt comfortable enough with shell scripting and familiar enough with the materials that I tried ad-libbing my way forward without the command. But after a few minutes I realized it really was necessary and so I had to pull a "don't ask questions just trust me this is the right thing to do :-)" which of course is...suboptimal.

I propose that the `basename` command be introduced, with some explanation and motivating examples, earlier in the materials. I will think about how that might be don, but for now I just wanted to get this out there. :-)

**Comment by taylorreiter** [comment]
addressed in #133 via https://github.com/datacarpentry/shell-genomics/pull/175. @fpsom, can we close this?

**Comment by fpsom** [comment]
Yes, I think we can safely close this. Thanks @taylorreiter !

I'll leave it open until the end of the week (just in case there are any objections), and close it then.

**Comment by fpsom** [comment]
No further comments, so I'm closing the issue!
