### ISSUE TITLE
Add set -e to Automating a Variant Calling Workflow shell script

### ISSUE THREAD

**Issue by shannonekj** [datacarpentry/wrangling-genomics#122]
It might be worthwhile to add ```set -e```  (exit upon failing) to the shell script we create in Episode 05:Automating Variant Calling Workflow. It is a great time saver!

**Comment by crazyhottommy** [comment]
agree, I usually do `set -euo pipefail` at the beginning of the shell script. I am not sure we should introduce one more concept here to overload cognitive burdens. I am open to this though.

**Comment by taylorreiter** [comment]
addressed in #133! @fpsom, can we close this?

**Comment by fpsom** [comment]
Yes, I think we can safely close this. Thanks @taylorreiter !

I'll leave it open until the end of the week (just in case there are any objections), and close it then.

**Comment by fpsom** [comment]
No further comments, so I'm closing the issue!
