### ISSUE TITLE
Setup webpage is nonfunctional

### ISSUE THREAD

**Issue by shannonekj** [datacarpentry/wrangling-genomics#124]
The landing page for https://datacarpentry.org/genomics-workshop/setup/ does not exist.
There are a few hyperlinks (mainly located on the initial https://datacarpentry.org/wrangling-genomics/ page) located throughout the lesson that try to link to the broken page.

**Comment by ErinBecker** [comment]
Thanks for catching this @shannonekj. Could one of the Maintainers please put in a PR to fix? @jrherr @crazyhottommy @malvikasharan @fpsom

**Comment by fpsom** [comment]
Thanks @shannonekj for pointing this out!

I've been trying to find the broken links, but so far all links to the setup page of the wrangling genomics lesson point correctly to the [existing page](https://datacarpentry.org/wrangling-genomics/setup.html). Would it be possible to direct me to the specific links that you encountered the issue?

**Comment by shannonekj** [comment]
@fpsom it look like the broken links were addressed and all the links all point to the correct https://datacarpentry.org/genomics-workshop/setup.html url now!

**Comment by fpsom** [comment]
Ok then! Thanks again @shannonekj , and thank you @ErinBecker for fixing them! :)
