### ISSUE TITLE
June 2019 Lesson Release checklist

### ISSUE THREAD

**Issue by fmichonneau** [datacarpentry/wrangling-genomics#157]
If your Maintainer team has decided not to participate in the [June 2019 lesson release](https://carpentries.topicbox.com/groups/maintainers/T61c75ac1a8a89538/timeline-and-process-for-june-lesson-release), please close this issue.

To have this lesson included in the 18 June 2019 release, please confirm that the following items are true:

- [x] Example code chunks run as expected
- [x] Challenges / exercises run as expected
- [x] Challenge / exercise solutions are correct
- [x] Call out boxes (exercises, discussions, tips, etc) render correctly
- [x] A schedule appears on the lesson homepage (e.g. not “00:00”)
- [x] Each episode includes learning objectives
- [x] Each episode includes questions
- [x] Each episode includes key points
- [x] Setup instructions are up-to-date, correct, clear, and complete
- [x] File structure is clean (e.g. delete deprecated files, insure filenames are consistent)
- [x] Some Instructor notes are provided
- [x] Lesson links work as expected

When all checkboxes above are completed, this lesson will be added to the 18 June lesson release. Please leave a comment on carpentries/lesson-infrastructure#26 or contact Erin Becker with questions (ebecker@carpentries.org).

**Comment by ErinBecker** [comment]
Hey Maintainers - just checking in to see if you're still planning on joining the release this month. We're asking that all lessons have completed the checklist by [Tuesday, 4 June, Anywhere on Earth time](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20190604T235959&p1=3399) in order to be included in the release. Please let me and @fmichonneau know if you have any questions or are running into any technical issues with preparing your lesson.

**Comment by fpsom** [comment]
Hi @ErinBecker ! Thanks for the reminder.

I just had a look, and I think that all of the items on the checklist can be ticked off.

There is an open PR #175 that addresses some minor points (as far as I can see). I've reviewed it as LGTM, so feel free to merge it.

The other open PR #171 is more formatting, but I cannot evaluate it. However, I do trust that it's an improvement, so I would also merge.

The final open PR #127 is probably obsolete, after the changes of the new release. So I would close, but will probably need the ok from the Shell genomics maintainers as well.

**Comment by ErinBecker** [comment]
Thanks @fpsom, sounds good to me! I've gone through those three PRs and either merged or recommended closing. I'll give the lesson just a once over to make sure things are rendered properly, but I didn't see any problems when we taught last week.

**Comment by ErinBecker** [comment]
https://datacarpentry.org/wrangling-genomics/02-quality-control/index.html
- [ ] The callout box "a faster option" isn't formatted. 

Other than that - all of the formatting seems ok to me.

**Comment by ErinBecker** [comment]
- [ ] There are no key points in the first episode. 
- [ ] I haven't checked the links.

**Comment by ErinBecker** [comment]
https://github.com/datacarpentry/wrangling-genomics/pull/177 fixes lack of key points in first episode (and also formats an unformatted challenge and adds solution).

**Comment by ErinBecker** [comment]
https://github.com/datacarpentry/wrangling-genomics/pull/178 fixes one odd link. Other links appear to work as expected.

**Comment by ErinBecker** [comment]
This lesson can be released after #177 and #178 are reviewed and merged.

**Comment by ErinBecker** [comment]
With the merging of #177 and #178, this checklist is now complete and lesson is ready for publication!

**Comment by ErinBecker** [comment]
Awesome work @datacarpentry/wrangling-genomics-maintainers and everyone else who contributed! This is just a quick message confirming that this lesson will be included in the release that @fmichonneau and I are preparing this week. The release is scheduled to go through on the 18th and to be announced to the community on the 24th. Please let us know if you have any questions! And congratulations again!

**Comment by fmichonneau** [comment]
lesson released! :tada: https://doi.org/10.5281/zenodo.3260609
