### ISSUE TITLE
wrangling-genomics/04-variant_calling: More problems with TVIEW

### ISSUE THREAD

**Issue by hoytpr** [datacarpentry/wrangling-genomics#179]
TVIEW does not look the same as lesson image. Suspect it's due to use of NC_012967.1 rather than CP000819.1. 

Therefore after pressing "g" one should enter "CP000819.1:4377265" not "NC_012967.1:4377265". The latter gives an error "Invalid"

![TVIEW_image](https://user-images.githubusercontent.com/5910884/59356091-c7477e80-8ced-11e9-9923-5e15bb704088.png)

**Comment by fpsom** [comment]
Fixed in PR #183. Thanks @hoytpr for catching this and @murraycadzow for the PR!
