### ISSUE TITLE
Which .md files to work on?

### ISSUE THREAD

**Issue by hoytpr** [datacarpentry/wrangling-genomics#18]
Could someone please tell me if the .md files (e.g. 00-readQC.md) in the primary /wrangling-genomics directory, or the /lessons/wrangling-genomics directory are under development?

**Comment by lexnederbragt** [comment]
Closing as http://www.datacarpentry.org/lessons/wrangling-genomics/ no longer exists. Files udner development are in https://github.com/datacarpentry/wrangling-genomics/tree/gh-pages/_episodes. Rendered version is http://www.datacarpentry.org/wrangling-genomics/.
