### ISSUE TITLE
When was FASTQC installed? 

### ISSUE THREAD

**Issue by Starbuck85** [datacarpentry/wrangling-genomics#185]
It isn't clear when FASTQC was installed? Is this done in another chapter? 

I'm running the data and I just get an error.

**Comment by ErinBecker** [comment]
Hi @Starbuck85 - thanks for reporting the error. Are you working on the Data Carpentry Amazon Machine Image on AWS? Or are you working locally? The lessons work best on AWS, which has all of the required software pre-installed. Instructions for setting up a copy of the image to work on are here: https://datacarpentry.org/genomics-workshop/AMI-setup/index.html. Please let me know if this solves your issue or if things are still unclear.

**Comment by Starbuck85** [comment]
Hi Erin,

Thanks for getting back to me!

I'm working locally. For some reason, we're not allowed to work on the
cloud. I know, I've tried to convince them its safe, but there are some
precedents in place because I'm looking at patient data.

Apologies, I didn't find things in the right order, mostly because I was
searching for a particular thing and missed out the linear set up.
I have somehow resolved the issue. I am using a mac so downloaded

   - FastQC v0.11.8 (Mac DMG image)
   <https://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.11.8.dmg>

I was hoping to understand the coding better, but running it this way is
probably better for someone with little experience.

Thank you for your help,

Lauren

**Comment by ErinBecker** [comment]
Glad you were able to find a solution to your problem! If you run into any other issues with software - the detailed setup instructions for working locally are here: https://datacarpentry.org/genomics-workshop/setup.html. Let me know if you have any other questions. Closing this issue. :-)
