### ISSUE TITLE
Fastqc issues [Submitted by email]

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/wrangling-genomics#187]
I have a question. Im doing the carpentries genomics curriculum. Now, when I try to transfer results of fastqc from my amazon instance to my desktop it denies me access. I have used the correct password, what could be the problem? 
Also, do I have to install all the required bioinformatics tools or some are preinstalled in the carpentries instance? Because I tried running the fastqc and it wasn't installed so I had to install it.

**Comment by fpsom** [comment]
Hi @ErinBecker !

I am not sure about the transferring of results between any cloud service and the local machine. I'm usually using either MobaXterm or WinSCP, and both work fine (you need to make sure that you include the keys created during the instance launch in the respective programs - and also that any firewall you might be working under, allows these connections).

For the bioinformatics tools, my understanding is that all of them are already included in the AWS instance - so again, I'm not sure why the `fastqc` command wasn't recognized....

Not really helpful, I know. Is there any chance of getting some information about the instance's details (such as which image was used to create it, etc)?

**Comment by fpsom** [comment]
Is there a follow-up question on this issue? Otherwise I'd like to close it if possible.
