### ISSUE TITLE
Extracting count matrix form the BAM files 

### ISSUE THREAD

**Issue by otienolwanga** [datacarpentry/wrangling-genomics#190]
Hi all! 

I have a question. 

If we want to extract **count matrix** from the `aligned.bam `files to proceed with **differential expression analysis** as a followup variant calling, how do we go about that?
Any resources or command-line scripts for this?

Thank you for your help.

**Comment by fpsom** [comment]
Hi @otienolwanga ! Thank you for this comment - however, I believe that it is a bit outside the scope of this particular lesson, as it's rather focused on Variant Calling as the paradigmatic NGS pipeline, which does not produce count matrices.

Moreover, the issue you are raising is rather broad; to my knowledge, there are several tools that can produce count matrices for given `bam` file(s). Additionally, they vary (a lot) depending on whether you are talking about transcript-based or gene-based counts. In any case, examples of such tools (regardless of context) include `htseq-count`,  `featureCounts`, `salmon`, etc. But I would really suggest that you pose this question to a wider audience (e.g. through `biostars`).

**Comment by fpsom** [comment]
Given that there was no further feedback / comments on this issue, I'll close it.
