### ISSUE TITLE
Description of boxplots in "Assessing Read Quality"

### ISSUE THREAD

**Issue by fsvarn** [datacarpentry/wrangling-genomics#195]
In the "Assessing Read Quality" lesson, there appears to be an error in the paragraph describing the boxplots (reproduced below):

"The x-axis displays the base position in the read, and the y-axis shows quality scores. In this example, the sample contains reads that are 40 bp long. This is much shorter than the reads we are working with in our workflow. For each position, there is a box-and-whisker plot showing the distribution of quality scores for all reads at that position. The horizontal red line indicates the median quality score and the yellow box shows the 2nd to 3rd quartile range. This means that 50% of reads have a quality score that falls within the range of the yellow box at that position. The whiskers show the range to the 1st and 4th quartile."

The yellow box described shows the 1st to 3rd quartile range rather than the 2nd to 3rd quartile range. The median is the 2nd quartile, and is depicted as noted by a horizontal red line. I believe the whiskers show the absolute range, which is the 0th to 4th quartile, rather than the 1st and 4th quartile as noted. Below is an edited version of the paragraph that accounts for these changes:

"The x-axis displays the base position in the read, and the y-axis shows quality scores. In this example, the sample contains reads that are 40 bp long. This is much shorter than the reads we are working with in our workflow. For each position, there is a box-and-whisker plot showing the distribution of quality scores for all reads at that position. The horizontal red line indicates the median quality score and the yellow box shows the 1st to 3rd quartile range. This means that 50% of reads have a quality score that falls within the range of the yellow box at that position. The whiskers show the absolute range, which covers the lowest (0th quartile) to highest (4th quartile) values."

**Comment by fpsom** [comment]
Hi @fsvarn ! That is an excellent point - nice catch! Would you be willing to put in a PR with these changes?

**Comment by fsvarn** [comment]
Hi @fpsom! Pull request has been created!

**Comment by fpsom** [comment]
Thanks @fsvarn ! Issue has now been addressed in PR #196 , closing now.
