### ISSUE TITLE
Typo in wrangling genomics 02-quality-control

### ISSUE THREAD

**Issue by hoytpr** [datacarpentry/wrangling-genomics#198]
Under "details of fastq format" the lesson reads:

"Each character is assigned a quality score between 0 and 40 as shown in the chart below."

should read:

"Each character is assigned a quality score between 0 and 41 as shown in the chart below."

**Comment by fpsom** [comment]
Thank you for this point @hoytpr - nice catch! Could you put in a PR for this?

**Comment by hoytpr** [comment]
Sure! Give me a just a little time.

**Comment by fpsom** [comment]
Thanks! PR #204 merged!
