### ISSUE TITLE
Provide files for rendering gh-pages

### ISSUE THREAD

**Issue by apawlik** [datacarpentry/wrangling-genomics#2]
Similarily to https://github.com/datacarpentry/excel-ecology this repository need _includes, _layout, css etc to render correctly in gh-pages

**Comment by michberr** [comment]
@tracykteal @mckays630 @kcranston Is anybody working on creating a functional website page for this lesson? I'd be happy to jump in on this over the next week.

**Comment by lexnederbragt** [comment]
Closing as it seems to be the case now.
