### ISSUE TITLE
04-variant-calling: samtools vs. bcftools typo

### ISSUE THREAD

**Issue by hoytpr** [datacarpentry/wrangling-genomics#201]
In 04-variant-calling, when starting `bcftools` a reference to `samtools` still exists:

The flag `-O b` tells samtools to generate a `bcf `format output file, `-o` specifies where to write the output file, and `-f` flags the path to the reference genome:

should read:

The flag `-O b` tells bcftools to generate a `bcf` format output file, `-o` specifies where to write the output file, and `-f ` flags the path to the reference genome:

**Comment by fpsom** [comment]
Thanks for catching this @hoytpr ! Do you think you'd be able to put in a PR?

**Comment by fpsom** [comment]
Fixed in PR #204
