### ISSUE TITLE
move multi-line commands callout?

### ISSUE THREAD

**Issue by aschuerch** [datacarpentry/wrangling-genomics#202]
I would prefer having the multi-line callout earlier in the lesson, i.e. when it first occurs, in
https://datacarpentry.org/wrangling-genomics/03-trimming/index.html. Now its at the end of https://datacarpentry.org/wrangling-genomics/04-variant_calling/index.html

**Comment by fpsom** [comment]
That is a good point @aschuerch ! Thanks for the PR as well - I'll review and merge.

**Comment by fpsom** [comment]
PR #203 merged, closing!
