### ISSUE TITLE
Update Variant Calling workflow

### ISSUE THREAD

**Issue by Talishask** [datacarpentry/wrangling-genomics#212]
I'm a member of The Carpentries staff and I'm submitting this issue on behalf of another member of the community. In most cases I won't be able to follow up or provide more details other that what I'm providing below.

------------------------------------------------------------------------

In the Data Carpentry Genomics Workshop in the Data Wrangling and Processing lesson, the fourth section is Variant Calling workflow. Under Step 2: Detect the single nucleotide polymorphisms (SNPs), the output file in the command:

$ bcftools call --ploidy 1 -m -v -o results/bcf/SRR2584866_variants.vcf results/bcf/SRR2584866_raw.bcf

The output file is a .vcf file and is put in the results/bcf/ directory. I am just wondering whether this file should be put in the results/vcf directory instead. This ensures students correctly follow organisation of files.

**Comment by ErinBecker** [comment]
Fixed with https://github.com/datacarpentry/wrangling-genomics/pull/228
