### ISSUE TITLE
wrangling-genomics/04-variant_calling: Viewing with IGV - typo

### ISSUE THREAD

**Issue by kalanir** [datacarpentry/wrangling-genomics#215]
Checkout submission:
In the following sentence from the episode: "We’ll put this folder on our Desktop for demonstration purposes, but in general you should avoide proliferating folders and files on your Desktop", "avoid" is spelled wrong.

**Comment by fpsom** [comment]
Thanks @kalanir - nice catch! Would you like to put in a PR to fix this?

**Comment by kalanir** [comment]
yes, let me do that!
