### ISSUE TITLE
Incorrect directory (bcf) under Step 3 in variant calling part

### ISSUE THREAD

**Issue by waydeveldman** [datacarpentry/wrangling-genomics#229]
Under https://datacarpentry.org/wrangling-genomics/04-variant_calling/index.html Step 3: Filter and report the SNV variants in variant calling format (VCF):
Replace "results/bcf/SRR2584866_variants.vcf" with "results/vcf/SRR2584866_variants.vcf"

**Comment by eltonjrv** [comment]
I've come across this same issue during a lecture this week.
Can anyone please fix it?
Thanks,
Best,
Elton

**Comment by ErinBecker** [comment]
Thanks for bringing this back to the top of the list @eltonjrv. This is now fixed with https://github.com/datacarpentry/wrangling-genomics/pull/228/
