### ISSUE TITLE
Worflow figure should include trimming

### ISSUE THREAD

**Issue by lexnederbragt** [datacarpentry/wrangling-genomics#24]
The figure used throughout `img/variant_calling_workflow_cleanup.png` should include a box for Trimming

**Comment by crazyhottommy** [comment]
+1:)

**Comment by ErinBecker** [comment]
The current figure includes a step called "quality control" with an explanatory text reading "Quality control - Trimming and/or filtering reads (if necessary)". Can this be closed?

**Comment by lexnederbragt** [comment]
Sure, at least for now (I'd prefer an update but then we would need to get our hands on the original svg files, if any...)
