### ISSUE TITLE
Automating a Variant Calling Workflow Issue Bonanza

### ISSUE THREAD

**Issue by fpsom** [datacarpentry/wrangling-genomics#26]
# Overview
- [x] Fix timing for Teaching and Exercises
- [x] Adapt the objectives to correspond to the lesson sections

# What is a shell script?
- [x] Change the formatting for the `code` parts of the main text.
> This looks a lot like the for loops we saw earlier. In fact, it is no different, apart from using indentation and the lack of the ‘>’ prompts; it’s just saved in a text file. The line at the top (‘#!/bin/bash’) is commonly called the shebang line, which is a special kind of comment that tells the shell which program is to be used as the ‘intepreter’ that executes the code.

# A real shell script
- [x]  Rephrase the name of the section to (e.g.) "Automating the previous FASTQC workflow with a script"
- [x] Explicitly add the `wget` command
- [x] Make sure that the `tree` command is installed
- [x] (maybe) restructure the rest of the section to two parts: "Variant Calling workflow" and "Automating the workflow"
- [x] Briefly explain the use of the three tools: samtools, bcftools and bwa.
- [x] Make sure that the three tools are installed (e.g. add the `apt-get` commands if necessary)
- [x]  Add links to the applications and version

# Key points
- [x] Add content

**Comment by ErinBecker** [comment]
I'm happy to take this on today.

**Comment by ErinBecker** [comment]
See also https://github.com/datacarpentry/wrangling-genomics/pull/79

We're no longer using `wget`or `tree`  in this episode.

Samtools, bcftools and bwa are explained in the earlier episode (where they're introduced for the first time).
