### ISSUE TITLE
Provide version numbers for software in setup?

### ISSUE THREAD

**Issue by aschuerch** [datacarpentry/wrangling-genomics#27]
The setup file should preferentially provide version numbers (that are compatible) for the software (where it matters). E.g samtools can vary quite a bit with versions there are combinations with bcftool versions that don't work.

Also, the setup for the whole DC genomics lesson could be combined? See datacarpentry/organization-genomics#30

**Comment by fpsom** [comment]
Yes, agreed. If this includes the data files, we might need to re-check and adapt the commands in all lessons. But for me this is essential for a coherent lesson.

**Comment by lexnederbragt** [comment]
Hmmm, we could set up some automatic testing, i.e. a makefile that runs the commands from the workshop so people can test their server/VM etc before they start their workshop... Maybe for later.

**Comment by mkuzak** [comment]
I agree with @lexnederbragt learners should be able to test if their setup is actually going to works. A lot of times in a workshop someone has prepared and expects that everything will work, unfortunately, it does not due to versions or some missing dependencies.

**Comment by ErinBecker** [comment]
See also #30 and #33

**Comment by ErinBecker** [comment]
Creating meta-issue in genomics-workshop. See link above.
