### ISSUE TITLE
Automating a workflow - referencing earlier parts of the workshop (Issue Bonanza)

### ISSUE THREAD

**Issue by aschuerch** [datacarpentry/wrangling-genomics#28]
To make the narrative independent from the workshop schedule and more applicable for self-learners, I suggest to replace references to parts of the day by references to the lesson itself.

"Now, let’s do something real. First, recall the code from our our fastqc workflow from this morning, with a few extra “echo” statements."
Replace by
 "Now, let’s do something real. First, recall the code from our our quality control workflow, with a few extra “echo” statements."

 "3) Bonus points: Use something you learned yesterday to save the output of the script to a file while it is running."
Replace by
 "3) Bonus points: Save the output of the script to a file while it is running (hint: redirection)"

**Comment by lexnederbragt** [comment]
Closed by #40
