### ISSUE TITLE
Move the contents to gh-pages

### ISSUE THREAD

**Issue by apawlik** [datacarpentry/wrangling-genomics#3]
For consistency Data Carpentry lessons are stored in gh-pages branch which allows to generate HTML pages via GitHub Jekyll. It would be good to apply this solution to this repository. The easiest way would be renaming master branch into gh-pages (though this will affect those who locally have only master).

**Comment by lexnederbragt** [comment]
Closing as this seems to be the case now or is otherwise outdated.
