### ISSUE TITLE
Figures page is missing

### ISSUE THREAD

**Issue by mkuzak** [datacarpentry/wrangling-genomics#31]
the link http://www.datacarpentry.org/wrangling-genomics/figures/ shows not content

**Comment by lexnederbragt** [comment]
I would hope this gets populated automatically. Would @rgaiacs know?

**Comment by rgaiacs** [comment]
> I would hope this gets populated automatically.

It isn't. You need to run some scripts. Please see https://github.com/datacarpentry/wrangling-genomics/blob/gh-pages/Makefile#L95.

I created https://github.com/swcarpentry/styles/issues/172 because I probably forget to issue it months ago.

**Comment by ErinBecker** [comment]
Other lessons in the DC stack have been removing the figures page from the lesson. This has been working well for the Ecology lessons and the instructor training materials. The images are still available in any case in each of the relevant episodes. I'll put in a PR to delete the figures page and wait for approval from @lexnederbragt @jrherr @crazyhottommy or @fpsom to merge.
