### ISSUE TITLE
Why does setup exist?

### ISSUE THREAD

**Issue by JasonJWilliamsNY** [datacarpentry/wrangling-genomics#32]
This seems to be in the SWC format. This lesson is midstream in whatever workshop flavor. There should be nothing for the user to download or install. Unless original intent of teaching all on cloud/HPC is changing this should part or workshop webpage template, or in a lesson that addresses this for learners installing these tools elsewhere.

**Comment by ErinBecker** [comment]
@JasonJWilliamsNY Thanks for catching this. I can see two ways to resolve this:

1) Remove the setup information and leave a note that all of the required software is already available on the cloud instance the learner will be using or

2) Make the note above but leave the setup instructions in case we have learners trying to use the lessons for self-directed learning (and don't have access to the AWS instance). 

Any advice on which of these makes most sense? @tracykteal @fpsom @jrherr @crazyhottommy @lexnederbragt

**Comment by lexnederbragt** [comment]
I'd appreciate if we can reach your number 2, but can imagine maybe waiting until after the release if getting it right takes a lot of time.

**Comment by ErinBecker** [comment]
Creating meta-issue in genomics-workshop. See link above.
