### ISSUE TITLE
Stage your data section redundant?

### ISSUE THREAD

**Issue by JasonJWilliamsNY** [datacarpentry/wrangling-genomics#33]
Episode: Quality Control

The Wrangling episodes (in my mind) come after the project organization. There will need to be harmonization between these sections, assuming that certain directories/prerequisites exist. Suggesting rephrasing to have a learner confirm that they have setup the appropriate directories.

**Comment by fpsom** [comment]
Maybe not directly relevant now/here, but I think that a general rethinking of the topics addressed in [both workshops](http://www.datacarpentry.org/genomics-workshop/) may lead to a more coherent and well-defined single workshop on genomics.

**Comment by ErinBecker** [comment]
I'll put in a PR to remove the stage your data section and replace with a reminder to the learner that we created these directories in a previous lesson (with link).

**Comment by ErinBecker** [comment]
Fixed with https://github.com/datacarpentry/wrangling-genomics/pull/69
