### ISSUE TITLE
Challenge idea for D. Document your work

### ISSUE THREAD

**Issue by JasonJWilliamsNY** [datacarpentry/wrangling-genomics#34]
Episode: Quality Control

When fastqc is complete, we gather all the summaries.txt. This would be a nice challenge to apply any learned shell commands to grepping on FAIL/PASS/WARNING in these results.

**Comment by ErinBecker** [comment]
This sounds like a great idea @JasonJWilliamsNY. I'll put in a PR to add a challenge question there.

**Comment by ErinBecker** [comment]
This exercise is now implemented as the last exercise in https://github.com/datacarpentry/wrangling-genomics/blob/gh-pages/_episodes/00-quality-control.md
