### ISSUE TITLE
Expand /possibly move IGV section of Varient Calling Workflow

### ISSUE THREAD

**Issue by JasonJWilliamsNY** [datacarpentry/wrangling-genomics#36]
There is no intro to what IGV is and too few instructions. Also, if this is in the Cloud, they need to connect to their instance using VNC. This might work best as  the very last thing in the workshop, I would consider moving.

**Comment by standage** [comment]
For the CSUMB workshop in March, I opted for `samtools tview` for visualizing the alignments and building up intuition for how variants are called. Worked just fine, samtools is already installed, and didn't require any Java business on the remote instance or local client.

**Comment by JasonJWilliamsNY** [comment]
That sounds nice. Of course it's good to know about IGV, but we don't have to introduce if there is a more straightforward way that accomplishes our learning objectives.

**Comment by lexnederbragt** [comment]
@JasonJWilliamsNY Can we close this one?

**Comment by ErinBecker** [comment]
Looks to me like this has been resolved. Thanks @JasonJWilliamsNY and @fpsom.
