### ISSUE TITLE
New Varient Calling Tools/Consider GATK

### ISSUE THREAD

**Issue by JasonJWilliamsNY** [datacarpentry/wrangling-genomics#37]
I know that newer versions of the tools we are using have deprecated some arguments we are using. Update? Also, now that GATK is going open, is it worth teaching this? I have never used it.

**Comment by crazyhottommy** [comment]
I was thinking why we are using bcftools to call SNVs. I have not used bcftools extensively. It is a genotyper caller the same as UnifiedGenotyper in GATK? for somatic mutations, I have used GATK (mutect1) recently, but it requires a lot of work to get a workable bam file: indel-realignment(mutect2 can skip this step but not stable yet), base quality recab etc... In a real world task with human genome, GATK is very slow, I have to parallelize every step by chromosome.

am working on a Snakemake pipeline on it for my own use: https://gitlab.com/tangming2005/snakemake_DNAseq_pipeline/tree/freebayes_anno

Best,
Tommy

**Comment by ErinBecker** [comment]
@tracykteal - This also sounds like a great question for the Genomics Curriculum Advisory Council. Can you please bring it to their attention?

**Comment by crazyhottommy** [comment]
Let's hold it for our next release. it requires a lot of work to re-write this part.

**Comment by DCGenomics** [comment]
Perhaps we could reference genome in a bottle as a list of curated pipelines for variant calling: http://jimb.stanford.edu/giab/

**Comment by ErinBecker** [comment]
Thank you for all of the great discussion on this issue. With the recent integration of a newer variant calling tool in Feb 2019 (https://github.com/datacarpentry/wrangling-genomics/pull/133), I'm closing this issue. Please reopen if I've misread and there is more to resolve here.
