### ISSUE TITLE
typos and additional exercise [datacarpentry/shell-genomics/#28]

### ISSUE THREAD

**Issue by aschuerch** [datacarpentry/wrangling-genomics#39]
From datacarpentry/shell-genomics/#28, raised by Asli Uyar: 

I have proof-read the lesson materials and noticed the following typos in the code or in the text:

https://github.com/datacarpentry/wrangling-genomics/blob/gh-pages/lessons/00-readQC.md”

 "it will help your remember what you did”

https://github.com/datacarpentry/wrangling-genomics/blob/gh-pages/lessons/01-automating_a_workflow.md:

 "First, recall the code from our our fastqc workflow from this morning”

**Comment by ErinBecker** [comment]
Split into two issues (typos and new exercise)

**Comment by ErinBecker** [comment]
These two typos do not appear in the current versions of these episodes and appear to have already been corrected.
