### ISSUE TITLE
Missing Twitter account WranglingGenomics 

### ISSUE THREAD

**Issue by peterjc** [datacarpentry/wrangling-genomics#43]
The README has the line:

> Follow updates on our *soon to be active* Twitter.

Which points at https://twitter.com/WranglingGenomics but that account does not exist yet

**Comment by ErinBecker** [comment]
Thanks @peterjc - I don't think there's a current plan to use that account so I would recommend we take out that line. @JasonJWilliamsNY @tracykteal @fpsom @lexnederbragt @crazyhottommy @jrherr do any of you know anything about this Twitter account?

I'll put in a PR to take this line out and wait for a maintainer to approve.

**Comment by crazyhottommy** [comment]
no I do not know.. I can register one for it if wanted.
