### ISSUE TITLE
Confusion over data-lessons vs datacarpentry GitHub accounts

### ISSUE THREAD

**Issue by peterjc** [datacarpentry/wrangling-genomics#44]
File https://github.com/datacarpentry/wrangling-genomics/blob/gh-pages/README.md ends with the text:

> Please cite as:
>
> Wrangling Genomics. June 2017. http://data-lessons.github.io/wrangling-genomics/.

However, the actual repository here is:

https://github.com/datacarpentry/wrangling-genomics

This is the "official" repository as linked to from:

http://www.datacarpentry.org/wrangling-genomics/

See also https://github.com/data-lessons/wrangling-genomics/issues/17 about what the ``data-lessons`` fork is for.

**Comment by peterjc** [comment]
The ``CONTRIBUTING.md`` file also has references to ``data-lessons``

**Comment by ErinBecker** [comment]
Thank you @peterjc for this issue. The data-lessons forks were created for early stage re-development of the datacarpentry genomics lessons, so as not to break anything in the repositories that were being used for live teaching. These forks are no longer active. They need to be checked to ensure that all updates are merged back into the datacarpentry repos and then deleted.

**Comment by peterjc** [comment]
OK, so I assume you'd welcome pull requests to update the remaining mentions of ``data-lessons`` to instead say ``datacarpentry`` (and then we can close this issue)?

**Comment by ErinBecker** [comment]
That would be fantastic! Thanks @peterjc

**Comment by peterjc** [comment]
OK, I'll try to do that later this week :)

**Comment by ErinBecker** [comment]
Thanks @peterjc !

**Comment by peterjc** [comment]
Should the "please cite" information be updated too?

**Comment by ErinBecker** [comment]
@peterjc - Yes. We usually wait to update that until right before publication, as we'll be adding the zenodo doi at that time.
