### ISSUE TITLE
Add instructor notes document for this lesson

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/wrangling-genomics#5]
I'm working on helping direct instructor attention towards fixing up/contributing to instructor notes. Currently don't have a link to provide for instructor notes for this lesson. Please add - even a blank document would be somewhere to point towards.

**Comment by lexnederbragt** [comment]
Blank page at http://www.datacarpentry.org/wrangling-genomics/guide/. Closing.

**Comment by ErinBecker** [comment]
Thanks @lexnederbragt
