### ISSUE TITLE
additional exercise about SAM format

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/wrangling-genomics#50]
An additional exercise for https://github.com/datacarpentry/wrangling-genomics/blob/gh-pages/lessons/02-variant-calling-workflow.md lesson could be: “Explore the content of sam file and find the first 6 mandatory fields listed in SAM format specifications: https://samtools.github.io/hts-specs/SAMv1.pdf “

Split from https://github.com/datacarpentry/wrangling-genomics/issues/39

**Comment by ErinBecker** [comment]
This will wait until after the lesson release.

**Comment by fpsom** [comment]
Closing in reference of #91
