### ISSUE TITLE
add time estimate for FastQC

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/wrangling-genomics#51]
I'm working through the lesson now and running FastQC using: 

`$ ~/FastQC/fastqc *.fastq`

So far it's completed 1.2 files (in about 5 minutes). I neglected to look how many files were in the set before running. Would be good to add a time estimate for instructors and self-directed learners so that they know how much time they have to work with while this is running. Possibly also give some directions about what would be useful use of time while learners are waiting for this to run.

**Comment by ErinBecker** [comment]
There are 6 fastq files. At this rate it will take about 30 minutes to run for all 6 files. I can only imagine that this isn't the intended scenario. Can anyone tell me what I'm missing? Is there a step to speed things up that I might have skipped? @k8hertweck @tracykteal

**Comment by k8hertweck** [comment]
My notes indicate it takes 4-5 minutes to run them all. The trick here is that there are two sets of the data, but one has been subsampled so the files are smaller and run faster. 

To set up the data I used:
`mv ~/.dc_sampledata_lite/untrimmed_fastq/ ~/dc_workshop/data/`

**Comment by ErinBecker** [comment]
Thanks @k8hertweck - I did remember that there were smaller versions of the files and I think those are the ones I'm running. Here is what I did:

dcuser@ip-172-31-58-54:~$ mkdir dc_workshop
dcuser@ip-172-31-58-54:~$ mkdir dc_workshop/data
dcuser@ip-172-31-58-54:~$ mkdir dc_workshop/docs
dcuser@ip-172-31-58-54:~$ mkdir dc_workshop/results
dcuser@ip-172-31-58-54:~$ mv ~/.dc_sampledata_lite/untrimmed_fastq/ ~/dc_workshop/data
dcuser@ip-172-31-58-54:~$ cd ~/dc_workshop/data/untrimmed_fastq/
dcuser@ip-172-31-58-54:~/dc_workshop/data/untrimmed_fastq$ ~/FastQC/fastqc *.fastq

**Comment by ErinBecker** [comment]
Markdown is parsing the ~ characters as strikethroughs. Please ignore that.

**Comment by ErinBecker** [comment]
Here are the file sizes for comparison: 

-rw-r--r-- 1 dcuser dcuser 840M Jul 30  2015 SRR097977.fastq
-rw-r--r-- 1 dcuser dcuser 3.4G Jul 30  2015 SRR098026.fastq
-rw-r--r-- 1 dcuser dcuser 875M Jul 30  2015 SRR098027.fastq
-rw-r--r-- 1 dcuser dcuser 3.4G Jul 30  2015 SRR098028.fastq
-rw-r--r-- 1 dcuser dcuser 4.0G Jul 30  2015 SRR098281.fastq
-rw-r--r-- 1 dcuser dcuser 3.9G Jul 30  2015 SRR098283.fastq

**Comment by fpsom** [comment]
The subsampled data files are available in the [variant_calling.tar.gz](https://github.com/datacarpentry/wrangling-genomics/blob/gh-pages/variant_calling.tar.gz) file, located in the root of the wrangling genomics lesson. If we have this file available from the beginning of the workshop (not necessarily the lesson), it should be easier to find and work with.

**Comment by ErinBecker** [comment]
@fpsom Thanks for that info. It turns out I was using the wrong disk image and had the large files. 

I still think we should include an estimated time for running the files. I can go ahead and time the new run and add that as a PR.

**Comment by tracykteal** [comment]
Adding a time estimate is definitely a good idea. Is there another issue that it's hard right now to figure out what set of files to run the FASTQC command on though?

**Comment by fpsom** [comment]
@ErinBecker unfortunately I've limited experience with that, so I cannot be of much help. I'll dig around though to see if I can figure the way.

**Comment by ErinBecker** [comment]
Actually - these aren't the right files either. According to the lesson text, the first read in the `SRR098281.fastq` file should be:

```
@SRR098281.1 HWUSI-EAS1599_1:2:1:0:318 length=35
CNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
+SRR098281.1 HWUSI-EAS1599_1:2:1:0:318 length=35
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

But I get:

```
Erins-MacBook-Air-2:trimmed_fastq ebecker$ head -n4 SRR098281.fastq 
@SRR098281.256 HWUSI-EAS1599_1:2:1:1:315 length=35
CTGGTGGTACTNTCTGTGGCG
+SRR098281.256 HWUSI-EAS1599_1:2:1:1:315 length=35
BA@A;?==B>=!BABA=3@AA
```

This is most likely because these are the trimmed files (and we're meant to be running fastqc on the untrimmed_fastq file.

**Comment by ErinBecker** [comment]
Actually . . . 

I'm now running FastQC on these files:

```
-rw-r--r-- 1 dcuser dcuser 840M Jul 30  2015 SRR097977.fastq
-rw-r--r-- 1 dcuser dcuser 3.4G Jul 30  2015 SRR098026.fastq
-rw-r--r-- 1 dcuser dcuser 875M Jul 30  2015 SRR098027.fastq
-rw-r--r-- 1 dcuser dcuser 3.4G Jul 30  2015 SRR098028.fastq
-rw-r--r-- 1 dcuser dcuser 4.0G Jul 30  2015 SRR098281.fastq
-rw-r--r-- 1 dcuser dcuser 3.9G Jul 30  2015 SRR098283.fastq
```

and it's only taking about 5 minutes to run through the whole set. These are the files that the lesson says to use, but the first time I did this analysis it took half an hour. I'm not sure what was going on, but the lesson instructions actually appear to be correct.

**Comment by tracykteal** [comment]
Thanks for following up on this. I don't know what was going on.
