### ISSUE TITLE
Explain commandline structure for samtools mpileup and bcftools

### ISSUE THREAD

**Issue by lexnederbragt** [datacarpentry/wrangling-genomics#56]
As per #25, we would like to add general commandline structure descriptions for the tools used. #55 addresses this for `bwa` and some `samtools` commands, but I don't know `samtools mpileup` and `bcftools` well enough to add some text for those.

**Comment by ErinBecker** [comment]
Closed with https://github.com/data-lessons/wrangling-genomics/issues/3
