### ISSUE TITLE
remove outdated files on the AMI

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/wrangling-genomics#78]
The trimmed FASTQs produced with we run Trimmomatic on our samples:

-rw-rw-r-- 1 dcuser dcuser 762M Nov  7 23:35 SRR097977.fastq_trim.fastq
-rw-rw-r-- 1 dcuser dcuser 2.7G Nov  7 23:36 SRR098026.fastq_trim.fastq
-rw-rw-r-- 1 dcuser dcuser 793M Nov  7 23:36 SRR098027.fastq_trim.fastq
-rw-rw-r-- 1 dcuser dcuser 2.7G Nov  7 23:37 SRR098028.fastq_trim.fastq
-rw-rw-r-- 1 dcuser dcuser 3.1G Nov  7 23:39 SRR098281.fastq_trim.fastq
-rw-rw-r-- 1 dcuser dcuser 3.0G Nov  7 23:40 SRR098283.fastq_trim.fastq

The trimmed FASTQs that are in the `variant_calling/data/` directory (produced from the `variant_calling.tar.gz` file):

-rw-rw-r-- 1 dcuser dcuser 46M Jul 31  2015 SRR097977.fastq
-rw-rw-r-- 1 dcuser dcuser 44M Jul 31  2015 SRR098026.fastq
-rw-rw-r-- 1 dcuser dcuser 45M Jul 31  2015 SRR098027.fastq
-rw-rw-r-- 1 dcuser dcuser 44M Jul 31  2015 SRR098028.fastq
-rw-rw-r-- 1 dcuser dcuser 44M Jul 31  2015 SRR098281.fastq
-rw-rw-r-- 1 dcuser dcuser 44M Jul 31  2015 SRR098283.fastq

**Comment by ErinBecker** [comment]
It's not clear to me why we have learners using the `variant_calling.tar.gz` file. I know this simplifies things so they don't have to create their own directory structure, but it also obfuscates the fact that they already have this data. I propose that we do away with the `variant_calling.tar.gz` file and have learners create their own directory structure and move their existing data into that structure. I'm happy to put in a PR for this if folks agree. This would fix this issue.

**Comment by crazyhottommy** [comment]
are the trimmed data there for people who are not able to run the trim step so they can just copy those?

**Comment by ErinBecker** [comment]
That was my initial thought, but they're really small. I noticed this because I went to view the alignment and variant calls after running the last script for the automation episode and there are so few reads in the small trimmed fastq files that it's a weirdly sparse visualization.

**Comment by crazyhottommy** [comment]
I agree. anyone else to confirm this? otherwise, we can do away with those.

**Comment by fpsom** [comment]
I think that the only major reason for keeping the reduced files in the tarball is to have an overall runtime of less than 5' (given that each sample is aligned to the genome). I haven't tried to run the whole process locally yet, so @ErinBecker will probably have a better idea of how long it takes for both cases.

If timing is not an issue after all, I'm also in favor of removing the file - but we still need to preserve the reference genome file that is also packaged within the tarball.

**Comment by ErinBecker** [comment]
@fpsom and @crazyhottommy - thanks both for your thoughts.

I haven't yet run the whole process on the full-size files, but will do that now and update this issue with how long it took. 

@fpsom - we don't need to retain the reference genome, as there is a copy provided in the `dc_sampledata_lite` directory: 
____________
# Setting up

First we will copy over the reference genome data into our `data/` directory. The `-r` tag used with `cp` means "recursive". This
allows you to copy over all of the files in a directory in a single 
line of code.

~~~
$ cd ~/dc_workshop
$ cp -r ~/.dc_sampledata_lite/ref_genome/ data/
~~~
{: .bash}

**Comment by ErinBecker** [comment]
Just ran the full workflow on all of the full-sized trimmed data-files (list below) in under 4 minutes. I recommend that we use that dataset for the exercises and get rid of the tarball. 

-rw-rw-r-- 1 dcuser dcuser 762M Nov 7 23:35 SRR097977.fastq_trim.fastq
-rw-rw-r-- 1 dcuser dcuser 2.7G Nov 7 23:36 SRR098026.fastq_trim.fastq
-rw-rw-r-- 1 dcuser dcuser 793M Nov 7 23:36 SRR098027.fastq_trim.fastq
-rw-rw-r-- 1 dcuser dcuser 2.7G Nov 7 23:37 SRR098028.fastq_trim.fastq
-rw-rw-r-- 1 dcuser dcuser 3.1G Nov 7 23:39 SRR098281.fastq_trim.fastq
-rw-rw-r-- 1 dcuser dcuser 3.0G Nov 7 23:40 SRR098283.fastq_trim.fastq

**Comment by ErinBecker** [comment]
Renaming to "remove outdated files on the AMI"

**Comment by ErinBecker** [comment]
List of files that need to be removed or updated: 

- ~/dc_sample_data/variant_calling.tar.gz

**Comment by ErinBecker** [comment]
@tracykteal and I went through the AMI yesterday and identified all of the unnecessary files. We're in the process of setting up a new AMI that is clean and only contains the files that we need for the current version of the workshop. When it is set up, we will put in a PR to update the reference to the AMI in the setup instructions.

**Comment by ErinBecker** [comment]
Related to https://github.com/datacarpentry/wrangling-genomics/pull/90

**Comment by ErinBecker** [comment]
Closed with https://github.com/datacarpentry/genomics-workshop/pull/34
