### ISSUE TITLE
double quoting bash variables

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/wrangling-genomics#81]
@crazyhottommy had included this in a list of issues. I've closed all of the other issues in the list and am moving this to its own issue. Would appreciate Maintainer feedback on this as I'm not familiar with style conventions for bash scripts.

-----

Always double quote your bash variable and use {}

```bash
$ for infile in *.fastq
>do
>outfile="${infile}"_trim.fastq
>java -jar ~/Trimmomatic-0.32/trimmomatic-0.32.jar SE $infile $outfile SLIDINGWINDOW:4:20 MINLEN:20
>done
```

**Comment by ErinBecker** [comment]
https://github.com/datacarpentry/wrangling-genomics/issues/23

**Comment by crazyhottommy** [comment]
I believe I read from the comments from this blog post http://www.kfirlavi.com/blog/2012/11/14/defensive-bash-programming

**Comment by ErinBecker** [comment]
I see what's happening here now and think this is a good addition. @crazyhottommy could you please put in a PR to convert the bash variables to this format? I can review and merge.

**Comment by crazyhottommy** [comment]
I think I accidentally pushed it... still getting myself with the PRs...

**Comment by crazyhottommy** [comment]
I should fork the repo first and push it to my own account and then request a PR. did not realize I can push to the main repo. good practice though..

**Comment by ErinBecker** [comment]
@crazyhottommy - no worries. I'll check your push and let you know if I see any problems. I've certainly accidentally pushed before!

**Comment by ErinBecker** [comment]
@crazyhottommy - I found just one typo and had a couple of small suggestions. I've made in-line comments on [your commit](https://github.com/datacarpentry/wrangling-genomics/commit/18eec4a6518867f1ecc21da70abcdee2a250a768)

**Comment by crazyhottommy** [comment]
Thank you! should I do another PR?

**Comment by ErinBecker** [comment]
Yes please!
