### ISSUE TITLE
need exercises in 02-variant_calling.md

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/wrangling-genomics#91]
The variant calling workflow episode has only one exercise. Need to add two more (at least).

**Comment by ErinBecker** [comment]
This can wait until our second release. There is a lot of hands-on live-coding in this episode, even though there aren't a lot of things marked as exercises.

**Comment by fpsom** [comment]
Adding here also Issue #50:

An additional exercise for https://github.com/datacarpentry/wrangling-genomics/blob/gh-pages/lessons/02-variant-calling-workflow.md lesson could be: “Explore the content of sam file and find the first 6 mandatory fields listed in SAM format specifications: https://samtools.github.io/hts-specs/SAMv1.pdf “

Split from https://github.com/datacarpentry/wrangling-genomics/issues/39
