### ISSUE TITLE
Illumina PHRED/Q-score inconsistent

### ISSUE THREAD

**Issue by hoytpr** [datacarpentry/wrangling-genomics#99]
line 93 says:
"uses the standard Sanger quality PHRED score encoding, using by Illumina version 1.8 onwards."
But images "good_quality.png" and "bad_quality.png" have "(Illumina 1.5 encoding)" across the top. Suggest altering the image titles as in attached files.
![bad_quality1 8](https://user-images.githubusercontent.com/5910884/33084933-d1c5f5d0-cea8-11e7-88b2-c0500c58783b.png)
![good_quality1 8](https://user-images.githubusercontent.com/5910884/33084937-d68f97c4-cea8-11e7-90a0-90723f836271.png)

**Comment by ErinBecker** [comment]
Thanks for catching this @hoytpr! I'm not sure how to download the data files linked into an issue. Would you mind putting in a PR to replace good_quality.png and bad_quality.png in the [img directory](https://github.com/datacarpentry/wrangling-genomics/tree/gh-pages/img) with these files?

**Comment by hoytpr** [comment]
@ErinBecker 
<https://github.com/datacarpentry/wrangling-genomics/issues?q=is%3Aissue+is%3Aopen+author%3AErinBecker> 
I put in the PR on a patch branch, but believe my repo was a few commits 
behind.

Peter

**Comment by ErinBecker** [comment]
Fixed with https://github.com/datacarpentry/wrangling-genomics/pull/106. Thanks @hoytpr
